Implement docs testing pipeline
GetStream/stream-video-swift pull request #277
Opened 2024-01-30 11:02 UTC by testableapple

### 🔗 Issue Links

_Provide all JIRA tickets and/or GitHub issues related to this PR, if applicable._

### 🎯 Goal

_Describe why we are making this change._

### 📝 Summary

_Provide bullet points with the most important changes in the codebase._

### 🛠 Implementation

_Provide a detailed description of the implementation and explain your decisions if you find them relevant._

### 🎨 Showcase

_Add relevant screenshots and/or videos/gifs to easily see what this PR changes, if applicable._

|  Before  |  After  |
| -------- | ------- |
|  `img`   |  `img`  |

### 🧪 Manual Testing Notes

_Explain how this change can be tested manually, if applicable._

### ☑️ Contributor Checklist

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] This change follows zero ⚠️ policy (required)
- [x] This change should receive manual QA
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (Docusaurus, tutorial, CMS)

### 🎁 Meme

_Provide a funny gif or image that relates to your work on this pull request. (Optional)_

2024-01-30 13:48 UTC, laevandus requested changes
Seems to be looking good except the CI failure about the StreamVideo import

2024-01-30 13:55 UTC, testableapple commented
@laevandus, sorry, was pretty sure that I marked the PR as a draft 🙈

2024-01-31 11:27 UTC, ipavlidakis approved these changes
🚢

2024-01-31 11:38 UTC, laevandus approved these changes

2024-01-31 11:59 UTC, merged